### ISSUE TITLE
Error Riding + Putting on Head

### ISSUE THREAD

**Issue by Enrick3344** [BlockHorizons/BlockPets#107]
@Sandertv 
Getting this error on trying to put the animals on my head

 `[23:35:50] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putBool() must be of the type boolean, null given, called in phar:///root/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/DataPacket.php on line 538" (EXCEPTION) in "src/pocketmine/utils/BinaryStream" at line 96`

On trying to ride them 

`[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'BlockPets v1.1.0': Argument 1 passed to pocketmine\utils\BinaryStream::putBool() must be of the type boolean, null given, called in phar:///root/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/DataPacket.php on line 538 on BlockHorizons\BlockPets\listeners\RidingListener
[23:41:36] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putBool() must be of the type boolean, null given, called in phar:///root/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/DataPacket.php on line 538" (EXCEPTION) in "src/pocketmine/utils/BinaryStream" at line 96`

========================================================
Also I've noticed I tried the Jeb_ Sheep and now when I spawn my wolf they are colored! like Orange and blue XD maybe fix that ;P

**Comment by Sandertv** [comment]
Wolfs are supposed to be colorful, just a fun feature. For the other errors; Have you made sure you're on the latest commit?

**Comment by Sandertv** [comment]
Oh nevermind, found it.

**Comment by Enrick3344** [comment]
@Sandertv Didn't know about the wolfs they are cute tho!

**Comment by isoz** [comment]
"Found it" ? and?
