### ISSUE TITLE
Snow Golem's Pumpkin has incorrect movement.

### ISSUE THREAD

**Issue by 95CivicSi** [BlockHorizons/BlockPets#108]
Server Details:
PocketMine-MP: 1.7dev-345
BlockPets v1.1.0 commit https://github.com/BlockHorizons/BlockPets/commit/55d7369958066ea3b4b288afff3a062ee24a077b

When a snow golem is looking around, the movements of the pumpkin on it's head are incorrect.  The pumpkin should rotate around it's own axis using yaw and pitch but instead acts as if it's on the top of an invisible stick.  This is more pronounced with larger snow golems.  In the video below, the snow golem was created with a size of 9.  This is easier to see if someone is riding the snow golem.

VIdeo Example is here:  
https://www.youtube.com/watch?v=QjR3872gwcE

**Comment by Sandertv** [comment]
I see, gotta lock the pitch of a snowgolem. Forgot about that, thanks! I see the snow golem also doesn't rotate around the yaw properly, or is that because it's being ridden? I can't tell.

Thanks!

**Comment by 95CivicSi** [comment]
It's being ridden.

**Comment by Muqsit** [comment]
https://github.com/BlockHorizons/BlockPets/commit/ee4ec012f850c961ed5d977143fef7621f90dbbf
