### ISSUE TITLE
suggestion for togglepetcommand

### ISSUE THREAD

**Issue by xkhhv** [BlockHorizons/BlockPets#118]
Hello

I have suggestion for togglepetcommand

can you make /togglepet on , /togglpet off , instead of just /togglepet , what i mean is separate on and off , make for everyone its args, i hope you make it.

**Comment by MalakasPlayzMC** [comment]
What if the pet is already on and you do /togglepet on

**Comment by Muqsit** [comment]
Closing because it's a duplicate of #113
