### ISSUE TITLE
ERROR PLEASE RESOLV THIS

### ISSUE THREAD

**Issue by dennisslol006** [BlockHorizons/BlockPets#130]
___ _ __   ___   ___  _ __
        / __| '_ \ / _ \ / _ \| '_ \
        \__ \ |_) | (_) | (_) | | | |
        |___/ .__/ \___/ \___/|_| |_|
            | |
            |_|

14:57:49 WARNING > [BlockPets] You are attempting to run BlockPets on a SPOON!
14:57:49 WARNING > [BlockPets] Before using the plugin you will need to open /plugins/BlockPets/spoon.txt in a text editor and agree to the terms.
14:57:49 INFO > Disabling BlockPets v1.1.0
14:57:50 CRITICAL > pocketmine\plugin\PluginException: "Plugin attempted to register BlockHorizons\BlockPets\listeners\EventListener while not enabled" (EXCEPTION) in "src/pocketmine/plugin/PluginManager" at line 735
14:57:50 DEBUG > #0 BlockPets_dev-234.phar/src/BlockHorizons/BlockPets/Loader(270): pocketmine\plugin\PluginManager->registerEvents(BlockHorizons\BlockPets\listeners\EventListener object, BlockHorizons\BlockPets\Loader object)
14:57:50 DEBUG > #1 BlockPets_dev-234.phar/src/BlockHorizons/BlockPets/Loader(238): BlockHorizons\BlockPets\Loader->registerListeners()
14:57:50 DEBUG > #2 src/pocketmine/plugin/PluginBase(90): BlockHorizons\BlockPets\Loader->onEnable()
14:57:50 DEBUG > #3 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
14:57:50 DEBUG > #4 src/pocketmine/plugin/PluginManager(567): pocketmine\plugin\PharPluginLoader->enablePlugin(BlockHorizons\BlockPets\Loader object)
14:57:50 DEBUG > #5 src/pocketmine/Server(1978): pocketmine\plugin\PluginManager->enablePlugin(BlockHorizons\BlockPets\Loader object)
14:57:50 DEBUG > #6 src/pocketmine/Server(1964): pocketmine\Server->enablePlugin(BlockHorizons\BlockPets\Loader object)
14:57:50 DEBUG > #7 src/pocketmine/Server(1758): pocketmine\Server->enablePlugins(integer 1)
14:57:50 DEBUG > #8 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Denniss\Desktop\PocketMine-MP\, string C:\Users\Denniss\Desktop\PocketMine-MP\plugins\)
14:57:50 DEBUG > #9 C:/Users/Denniss/Desktop/PocketMine-MP/PocketMine-MP.phar(1): require_once(string phar://C:/Users/Denniss/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by Driesboy** [comment]
A SPOON RUNNER!!!

**Comment by dennisslol006** [comment]
WHAT?

**Comment by 95CivicSi** [comment]
What version of PocketMine-MP are you running?

**Comment by dennisslol006** [comment]
I HAVE ALTAY 1.2.11
