### ISSUE TITLE
InvMenu and libasynql compatibility / reliability

### ISSUE THREAD

**Issue by notacoderr** [BlockHorizons/BlockPets#139]
Hello, First thing is i would like to test this but i can't, somehow even tho both **InvMenu & libasynql** is properly installed, as far as i know (../virions/ ) and DEVirion aswell. It still says Classes for both aren't found which disables the plugin. Any tip may help.

_

> - ShockByte
> - PocketMine-MP 1.7dev-1079

_

**Comment by Muqsit** [comment]
Just use the pre complied phar file instead

**Comment by Muqsit** [comment]
https://poggit.pmmp.io/ci/BlockHorizons/BlockPets/BlockPets
