### ISSUE TITLE
Disable hit if player can not be hitted

### ISSUE THREAD

**Issue by Driesboy** [BlockHorizons/BlockPets#15]

**Comment by Sandertv** [comment]
You'll have to explain that a bit more.

**Comment by Driesboy** [comment]
in dutch?

**Comment by Driesboy** [comment]
als de speler niet gehit kan worden dan de pet ook niet

**Comment by Sandertv** [comment]
Oh op die manier, ik weet niet zeker hoe ik dat goed kan maken. Ik zal het proberen.

**Comment by Driesboy** [comment]
ja ik zou dat ook niet weten

**Comment by Driesboy** [comment]
@Sandertv kan je deze bug fixen? https://github.com/NL-4-DEVS/Eggwars/issues/40
