### ISSUE TITLE
Pets multiply when teleporting to new worlds

### ISSUE THREAD

**Issue by Dblcut3** [BlockHorizons/BlockPets#16]
So I have a strange glitch. When you teleport to a new world, your pet follows you. But, theres an odd glitch where that pet becomes several duplicates of it and it causes insane lag. Any ideas on how to fix this?

**Comment by Sandertv** [comment]
Could you please look into console when this happens and check if there's any errors?

**Comment by Sandertv** [comment]
Okay they didn't duplicate for me when switching worlds, but when the server restarted. I'll try to find the issue.

**Comment by Sandertv** [comment]
Have you tried the latest version of the plugin? The latest Poggit version isn't updated, so try to use devtools to compile it yourself. It should have your bug fixed hopefully.
