### ISSUE TITLE
Crash server since Update

### ISSUE THREAD

**Issue by errox404** [BlockHorizons/BlockPets#167]
Error: Declaration of BlockHorizons\BlockPets\pets\BasePet::getAttackDamage(): int must be compatible with pocketmine\entity\Living::getAttackDamage(): float
File: PetsLbsg.phar/src/BlockHorizons/BlockPets/pets/BasePet
Line: 34

Crashdump

**Comment by Muqsit** [comment]
You're definitely not using the right software.
