### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by SerezhaIvanov** [BlockHorizons/BlockPets#17]
20:46:23 [CRITICAL] ErrorException: "Declaration of BlockHorizons\BlockPets\pets\IrasciblePet::attack($damage, pocketmine\event\enti
y\EntityDamageEvent $source) should be compatible with pocketmine\entity\Living::attack(pocketmine\event\entity\EntityDamageEvent $s
urce)" (EXCEPTION) in "/plugins/BlockPets/src/BlockHorizons/BlockPets/pets/IrasciblePet" at line 14

Core: Tesseract

**Comment by SerezhaIvanov** [comment]
Bug appears when server is starting

**Comment by Sandertv** [comment]
Tesseract is not supported. This change comes from PocketMine 3.0.0-ALPHA6, which the plugin does not support yet.

**Comment by SerezhaIvanov** [comment]
Ok

**Comment by SerezhaIvanov** [comment]
What files I need to edit to work?
