### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chaosfreak93** [BlockHorizons/BlockPets#170]
Warning: Uncaught ErrorException: Declaration of BlockHorizons\BlockPets\pets\BasePet::initEntity(): void should be compatible with pocketmine\entity\Living::initEntity(pocketmine\nbt\tag\CompoundTag $nbt): void in phar:///home/mcpe/TestServer/plugins/PetsLbsg.phar/src/BlockHorizons/BlockPets/pets/BasePet.php:34
Stack trace:
#0 phar:///home/mcpe/TestServer/plugins/PetsLbsg.phar/src/BlockHorizons/BlockPets/pets/BasePet.php(34): pocketmine\utils\Utils::errorExceptionHandler(2, 'Declaration of ...', 'phar:///home/mc...', 34, Array)
#1 phar:///home/mcpe/TestServer/Altay.phar/vendor/pocketmine/spl/BaseClassLoader.php(126): include('phar:///home/mc...')#2 [internal function]: BaseClassLoader->loadClass('BlockHorizons\\B...')
#3 phar:///home/mcpe/TestServer/plugins/PetsLbsg.phar/src/BlockHorizons/BlockPets/pets/IrasciblePet.php(18): spl_autoload_call('BlockHorizons\\B...')
#4 phar:///home/mcpe/TestServer/Altay.phar/vendor/pocketmine/spl/BaseClassLoader.php(126): include('phar:///home/mc...')#5 [internal function]: BaseClas in phar:///home/mcpe/TestServer/plugins/PetsLbsg.phar/src/BlockHorizons/BlockPets/pets/BasePet.php on line 34

Fatal error: Declaration of BlockHorizons\BlockPets\pets\BasePet::getAttackDamage(): int must be compatible with pocketmine\entity\Living::getAttackDamage(): float in phar:///home/mcpe/TestServer/plugins/PetsLbsg.phar/src/BlockHorizons/BlockPets/pets/BasePet.php on line 34

**Comment by Muqsit** [comment]
Don't use dev builds, you aren't supposed to be using PocketMine v4.0.0.

**Comment by chaosfreak93** [comment]
I use Altay 4.0.0
