### ISSUE TITLE
pet level up

### ISSUE THREAD

**Issue by RubyTemple** [BlockHorizons/BlockPets#173]
[22:18:39] [Server thread/CRITICAL]: TypeError:
 "Argument 1 passed to BlockHorizons\BlockPets\
pets\BasePet::addPetLevelPoints() must be of th
e type integer, float given, called in phar:///
root/test2/StartPmmp/plugins/BlockPets_dev-268(
1).phar/src/BlockHorizons/BlockPets/pets/BasePe
t.php on line 297" (EXCEPTION) in "plugins/Bloc
kPets_dev-268(1).phar/src/BlockHorizons/BlockPe
ts/pets/BasePet" at line 370

**Comment by Emis02** [comment]
Help?

**Comment by artulloss** [comment]
type cast it... use (int) in front of the problematic variable that is a float but needs to be an int.

**Comment by Emis02** [comment]
pet doesn't level up

**Comment by ericsimard52** [comment]
Same as: https://github.com/BlockHorizons/BlockPets/issues/158

**Comment by lukeeey** [comment]
Duplicate of #158
