### ISSUE TITLE
Is development still alive

### ISSUE THREAD

**Issue by ericsimard52** [BlockHorizons/BlockPets#177]
Happy new year.
Is development of this plugin still alive? I have the same issue of crashing server when this plugins is installed with PureEntityX.
I am atempting to find a fix. Wondering if someone with previous experience can help.

**Comment by Sandertv** [comment]
Happy new year. I'm sorry to say the development of the plugin is inactive at the moment. I don't have the time to update it at this point, and it seems neither does @Muqsit.

**Comment by ericsimard52** [comment]
Thanks for the quick reply. And it's not a bad thing, I have been looking for a good starting point to contribute to a project related to Minecraft. I have forked this plugin, I would like to maintain it. I have previous experience with PHP which will help, but I have never touch poggit plugin code for PocketMine-MP. 
Would you mind if I post for guidance when I am stuck? I don't mind waiting for help. 
I am stuck at the moment, and could use some guidance. But if you have no interest and no time for this plugin I understand and will keep hacking at it until I understand it.

**Comment by Muqsit** [comment]
https://github.com/BlockHorizons/BlockPets/issues/147 might be related, if it's a runtime crash.
