### ISSUE TITLE
Building Phar manually

### ISSUE THREAD

**Issue by ericsimard52** [BlockHorizons/BlockPets#178]
I have Poggit-CI setup, but because I don't know what I am doing yet, I make too many commit I need to be able to create the Phar file by myself.
I am having issue with including some libs:
InvMenu  libasynql  spoondetector
The phar I built starts but complains right away about spoon detector.
I cloned those repos, and attempted to statically include them with BlockPet in src folder. If that was to work I would have excluded them from git until I can figure the proper way to do it. But the further I made it was an error with mysql. Should this have worked?
I attempted to see if I could find a log with the commands used by Poggit CI to build it but to no avail.
Would anyone have a previously working command or a descent documentation link. I found quite a few, but none that gave me the desired result.

**Comment by ericsimard52** [comment]
I got further, I have the following plugins installed:
DEVirion 
Sheep
PocketMine-DevTools
VirionTools

I think with those I should be able to copy the BlockPet directory I am working on in the plugins folder and load it. I have in virions folder InvMenu  libasynql  spoondetector
The plugins load, I crash as soon as my player logs in. 
I must be missing something. 
But before I continue I would like to have confirmation that I am going in the right direction.

**Comment by ericsimard52** [comment]
I have made progress I have it running from source, I have the git master branch of InvMenu  libasynql spoondetector in virions folder.
I needed to change PetInventoryManager.php construct to:
`
	public function __construct(BasePet $pet) {
		$this->pet = $pet;
		$this->menu = InvMenu::create(PetInventory::class); // Removed InvMenu::TYPE_CUSTOM
		$this->setName($pet->getPetName());
		$this->getInventory()->setManager($this);
	}`
TYPE_CUSTOM is no longer in invmenu.
Once that has been changed, I am back to the original issue with PetOwner tag!
I guess that is a good step forward.

**Comment by Muqsit** [comment]
@ericsimard52 Oh, yeah the new InvMenu version has that change. I guess you can move the onClose method from PetInventory to PetInventoryManager and use InvMenu's inventory close listener like so...
```php
class PetInventoryManager {
    public function __construct(BasePet $pet) {
        //...
        $this->menu->setInventoryCloseListener([$this, "onClose"]);
    }

    public function onClose(PetInventory $inventory, Player $player) : void {
        //port code from PetInventory::onClose() here
    }
}
```
This will make calling `PetInventory::setManager()` unnecessary and also remove the need of PetInventory class to exist. It could be replaced by `InvMenu::TYPE_CHEST` instead of `PetInventory::class` but I guess it can be kept back for plugins to handle pocketmine's inventory events for pet inventories.

**Comment by ericsimard52** [comment]
Thanks for the info. Will take me some time to wrap my head around it all, but I'm making descent progress.
