### ISSUE TITLE
Conflict with MultiWorld

### ISSUE THREAD

**Issue by ericsimard52** [BlockHorizons/BlockPets#179]
When changing world, fatal error happens if I fly too far away from my pet.
It does so when attempting to tp my pet to me.
`[Server thread/CRITICAL]: Error: "Call to a member function broadcastPacketToViewers() on null" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1189`
I have not found a work around yet, I am looking to see if I can update the missing info from within this plugin.

**Comment by Muqsit** [comment]
I'm not sure about this issue either but I plan on shifting pet movement handling methods to `BasePet::updateMovement()`. Pocketmine calls this in it's `Entity::onUpdate()` and that's probably the right way to do movement updates. The rest of the non-movement methods could be moved to `Entity::entityBaseTick()` after overriding the method.

**Comment by ericsimard52** [comment]
I removed Multiworld, this issue is still occured.

**Comment by Ifera** [comment]
Should be fixed with the latest update. If not then please do make a new issue.
