### ISSUE TITLE
Adjust following from player behavior

### ISSUE THREAD

**Issue by ericsimard52** [BlockHorizons/BlockPets#180]
This would be an enhancement that I would like to implement.
When the pets follow the player a little distance in between them would be more enjoyable.
Also, I would also like to somewhat fix the pets behavior with water block, lets just say they are good at getting in, not soo much at getting out. Also a wolf can swim, I would like to avoid having them sink if possible.

**Comment by Ifera** [comment]
Should be fixed with the latest update. If not then please do make a new issue.
