### ISSUE TITLE
Crashed the server (LASTEST JAN 19 PM VERSION)

### ISSUE THREAD

**Issue by Flucid** [BlockHorizons/BlockPets#185]
PocketMine-MP Crash Dump Sat Jan 19 15:13:45 EST 2019

Error: Tag with name "petOwner" not found and no valid default value given
File: vendor/pocketmine/nbt/src/tag/CompoundTag
Line: 188
Type: RuntimeException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: BlockPets v1.1.2

Code:
[179] 	 * @return mixed
[180] 	 */
[181] 	public function getTagValue(string $name, string $expectedClass, $default = null, bool $badTagDefault = false){
[182] 		$tag = $this->getTag($name, $badTagDefault ? NamedTag::class : $expectedClass);
[183] 		if($tag instanceof $expectedClass){
[184] 			return $tag->getValue();
[185] 		}
[186] 
[187] 		if($default === null){
[188] 			throw new \RuntimeException("Tag with name \"$name\" " . ($tag !== null ? "not of expected type" : "not found") . " and no valid default value given");
[189] 		}
[190] 
[191] 		return $default;
[192] 	}
[193] 
[194] 	/*
[195] 	 * The following methods are wrappers around getTagValue() with type safety.
[196] 	 */
[197] 
[198] 	/**

Backtrace:
#0 vendor/pocketmine/nbt/src/tag/CompoundTag(283): pocketmine\nbt\tag\CompoundTag->getTagValue(string petOwner, string pocketmine\nbt\tag\StringTag, NULL , boolean )
#1 plugins/BlockPets_dev-268.phar/src/BlockHorizons/BlockPets/pets/BasePet(110): pocketmine\nbt\tag\CompoundTag->getString(string petOwner)
#2 plugins/BlockPets_dev-268.phar/src/BlockHorizons/BlockPets/pets/IrasciblePet(28): BlockHorizons\BlockPets\pets\BasePet->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
#3 src/pocketmine/entity/Entity(328): BlockHorizons\BlockPets\pets\IrasciblePet->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
#4 plugins/TeaSpoon_dev-265.phar/src/CortexPE/tile/MobSpawner(90): pocketmine\entity\Entity::createEntity(integer 12, pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
#5 src/pocketmine/level/Level(839): CortexPE\tile\MobSpawner->onUpdate()
#6 src/pocketmine/level/Level(770): pocketmine\level\Level->actuallyDoTick(integer 2470)
#7 src/pocketmine/Server(2451): pocketmine\level\Level->doTick(integer 2470)
#8 src/pocketmine/Server(2598): pocketmine\Server->checkTickUpdates(integer 2470, double 1547928825.551)
#9 src/pocketmine/Server(2346): pocketmine\Server->tick()
#10 src/pocketmine/Server(2209): pocketmine\Server->tickProcessor()
#11 src/pocketmine/Server(1785): pocketmine\Server->start()
#12 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/pocketmine/, string /root/pocketmine/plugins/)
#13 (1): require(string phar:///root/pocketmine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.5.6 [Protocol 313]
Git commit: d4851a8f1f076856a25daafa6796f572c909a905
uname -a: Linux vps211022 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64
PHP Version: 7.2.13
Zend version: 3.2.0
OS : Linux, linux

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtXI1z2zaW/1dwcubW6Yj6tGxZHffOsZ0mrZ3oYqXp3nInA5GQxJokWIK0rO71f7/3HkASpOVE
cdzdm5vubGMRBB7eF977PRDkP1oLmUY8+3grUhXIuDUZtFtZEInWpD86ODoejMeDUbsVcpVdpKlM
W5N/tLJNArdb7/IYO17ceSLJcGi7FQml+BJvzviSrYNsxWIeCea2EpG9XccidVsslhlbyDz2GYf/
YslueRj4zBcLnocZXuWCLYNbgRQXeRi+DEIkmax4Oul2u6mUWTeR3o3IoiAW3Sn9vIKfztW0g726
MNaXqd0pnmddlXrdjC+7ZzJKcH7gEbonOIueYedhMCSE26Cj8RjUlXIPfv+ttddjO5PYH4yHzyes
6ui60NN1oZvrWv2c75Yig78/oVr2VZYG8ZIV2myzomErmWu6CYPb7M37y0vWZnMpQ8Fj9hwk2Ouz
JMyXQay6L0IYPxWZ+uiLW2dwONZqRLbp1iuZBr9Ju2M3wX9ecCXgar/f7+0si2aqKQkxNPhqhl6n
XHnBPCSuBmNgqtbddcv+rpvQv0YE57uPHz3okaW5l+3bkoTiVoSue4l/mJz/Irys/XlRTU8Sa8iQ
b8slBCycbNO9oD/7w534tCX7I5k9KG0wE/w6kTI2JhhVJjiTaSbuphfdDNZN90rOrxOORtw/brqB
ltR1taiTiZcKngkjeBBnYilS1h/Uefx6IUZNjRPJLlHcHw+PgctCBiAEQrhuJYXznYzfJz7wuU/E
Dj9F7OioKbLNvfMd97Kch+HmXM4C76YUeXAA45D4UZP4tUghFO8PDkb9TxL2HyA4fojg6HjcIKjv
ON95K+HdIDUttaoRbTNf5uB2rEoHnRHwhnMdPzTX8ODwgbkyZFpHn95Dowe940+MnqbSgzQjU0Om
/wCZ/tF49AAZlfE0M8MHzeFVOgEjPMSIvf4wgpxBglSXkvugtW0em4OTwSK+4kF8KZdLq5eJg/ey
2sN3ivWp+R+yfXSUVPyaB2mVIHbPlQ+Kj7nxeevvv7db4l+S+b8iJwPPWksfg/hWhrcigkAExILY
ByV5Wau4D21lpIVGT/oC5ewfHcMdN2PfsP9MRZanMYuCO+FDl/64Z2516apPVwkskcBjizz2UCFs
S85+hvoorfpM3CXAiPDJc9rsWaGEExYD5NGZmj2bcxTtvLy34KESz/9BMw9oZjd7BoqAW8+yVaAK
tLBvZmsQ+A/2BpqxBUIxTswmDU6ef0u0h4Z2sNgn8uBvGY89IRfN/pqXA9PfzYy6cBQxo3VgyI5M
t9/p6hCu6MeRNVuphxOtCTPBuJwgW6VyzWKxZq7bdMR9t+l+rtsiVeAPcEbWYVqgfzPkQSVuC/0S
JCsEY+jm0HdibpHLuq3nMBhaP+e60FELe2wLe9wzwh73TXOhKEOCxhxrm+oRw2KEVm73G7oYFY45
WwngLAzlGv0pEtlK+orxVLB1ypME4Dxc0GKznfG5Vg5KyBRfiGzTIbKHtlMfHxVTj83U37R+/xPn
/olz/8S5f+LcP3Hunzj3/yPObbeWAlYFDxEAImSA1FcjA2zMQQXVTllr2Bl1DrE5D0IfgOfR8Kjd
CiiWtyYE1QBnpjKTngSqw/4Q5ggQh/oH41Gfjxf9Re/ocDw65IORz/mCHx4dHy5GRwPvuHfMj3sj
oJ3ymzCYw5hepz/o9KAlN8xdBnF+x24TNYC0NBiwg05/1Ok5B0OHBAE4undw6LyfA0bK2fXVFBBD
zs6Fxw5Z/2ByMJoMxuz97IwNev0xuxsffjw8QFy8SoD2UWfQ6Q/h8jfI8ySpnhvufpSqmBwa6CKk
ixJ0K9Tg94BBQnEGediX69jSaeNGu1XpE+bo9KGF5wBmUoVQ44wnGTjTee7doIl4EmDrEDr28FrE
HNYscAguCsr2RQL84kC4p+QiO7cbIk6A39MkfSDpunVumtdYU4Czoye8vZ59ePvu8hya1mKuggxl
QZnPxe0MuitLxLLJFq4PCm1KV/kXgywUPZWExfyua3FiBLmenb6bvZ/WxFhlWaJgGYFzrvJ5x5OR
tTy6JQ0Q9gNPEwWRyRK2bGoI25Q1Dm6kuoG7TyRkMa/rWhx81loXEM9ktDmdvrZEsBptIUYdWAZ1
IWQs5vDfU8lgyAF+0BwATcAQNjefFej0g0xD/4VMISRbItWa65ZpiAS+fhOAx/v3pWrT3775OzB/
h+bvgfk7Mn8xEh58jTYqTlzX5l/nk12UMRNR8oLH723jVm11NRzX1XANeY7/dbZFB18lkyHruiUb
u0tzBWVhQHqwxLEa6/KMiFnbsL8JbzW9guWLy/+n4C64OftveqSyyTOV3wTw+waq2OBGPZU/R8jc
GpkDKW1GPynrlvBj8d61CIFSXqRAyuMqq7m73dpQS10pF7cyvAbun0pia2IoZmpc7BBw1+t1RwBH
SL2T3aB8U8HTcEvarLfXZew1TX+KSewcAbRMFO1YAA95GEr1ZKb+WcQyWQVh4EHZU2OucblTEIs3
65VIxQvu3STwnx3Imrfqog+bot/IlPtyNOxHRzVRMfc+UlSLJASmBj/3W3Za2ptsFXjvBKjPBg61
5pqgdSHPQa8vodyaXj2VjPbMkIJuoaDVMH8XaabBcrk5y1Umo4vYW/E4U9crmdje+0CPRmZqYoZz
DgO/zzc1KQdfAYwMPXDR7QztHpyvPZmKV7kdmsumJqZtuOgP4CRX50+1EDU1KNnM7F+QX86mFzN5
HigYWUsxtfa6iQ7ui5KtxIrf3Qz6W/FD//E++QMtL8MHMrW7aNM8FVORRvbiqtoaInUGjjfgdcEO
D16+7PXYvzPAlVjAvo4XQRxkm6ey2kc9AThiwZX18xEJk8aagrmig4CXq80rGQlbE1VbM48M/hme
Wk6/uz1/PH9n8Y9Xn8mAfwznMDH9swvLb+RsavFMl02mj+pM8/VvfP1UPBMx141ltmNU2+JVmiFM
0Hkmz0JI65d8ubSzc639M3FvKjOeyScrnmpzP1pEw9QsheF/nXXrAoHkL4XKgtvarlDZ1DTn2PHF
bWMJfS/iuXyysLEkaq5bsPBosTWhbikKFU96H7xWO5mmpqTNXRqzyVwTc/T4yF9tWtfF+xSWLsZ0
7ja/UaHAVeC9en9uVwlF0z3DNdZhGOThk9lMU3Pd1a65edtCDMUvAONTCbSsXUyn2CPNUiG6EVUe
3VLKEpmluNt9D43p1mYu7P1zERgxsXse0IjtBxnYXmo1fgIzn6pfY44ooiZK32xvILJ5bBwqCO8u
BkaZ1/FtI5Biiy1ADxfalrz2RgIeWuXBk9VyvwDRuCDqujAd6PIWKpuSqc9K9ILHwFfdzaq2z2zy
noJnC65eff/jF0lk79t9yj4ldXwKaliyfu7kdysOEBBWVz0T1Jo/EyP/6MLU5qV+tdPOGVTr70TC
A3tXxWq8BxSd4ZZth9QTubri2ZNtr1QcPD50ElMRMrW9VP10mXovQP4rS9QvKE8zvligE9j1adnW
3KpvVHWzVR5D6T8cDg9GT2ZJiyae2DCsWD8fYVtD9FwKVRQ/FTmMs2HA1Tsxl6mdL+zWf5FfWyw8
kWP/NH3zfc5rdXzZdK/scBKeeauGJ8+5SlKJuzJPJGRJ0HUtVj4B5WhT4u3s/HqVLxahsLckrNam
8x42nVeci2AuG1IMHr0zVk29CxwlGfgy8D5c2Pyblnp6v4e2fhZxwMNzfu8hmXN6OX11emSetJjL
cXH5aNE0V7uKdSajOc/0c307CdrNTfxyeB++sD8av3jEUEgM0dEZm73PIxmRQdr8SWZBbFe6tebP
bJvM1gEgcf+pUoIhB5DF4qF+tSuGufZSHgEDaQPEVO2fe7LwuFC4I1SrsfJEgfEy9242dMzMktlq
bHpsw5ZTKL0ARzVsOfwyWzbEN9Ia0q5bcfP4bQzDZlkjfVhB3xAc5x1gX3m/XGreb9r9oFk9KQ51
ZQwZfHTQPYV/nOmrew7eprL/8VkRJlHFJLBytzG6u4bqCipYxhVenvi2lrd1CryeXhr+UDu/+GRP
ER88FPkFD2FSiUfma8++qzZbqoP7D1pexwuRxrnq9/pPJZNF8kvr+/NUJuqex+rWT1T4FxEe3/Kv
zrY+iBg8vsIvCRc+SazsLtUbORNhWN8Mxoamqw3/KdvBMPMTbAiHa75RdJK0hqyr1nrNP2gGlCk+
O07YNfwJMYE9kZj0SDpRhqrrcuJIIUf3F9NDQOfUv8WXHfwfg1qMqDXXDwoNmrYLc48Pxon4yoqh
9tBqe3X6UqZRPa/YfD7a0qUA3ZrYuCPO6R2XxjEwu7Vu+nshdCYyfF7uf2wz4Qf4wsV8w366ml4w
c2QB39Z5ggNxpDxTWZ7GWQB+GWn2tqZjSwLXNRdf8ryxUW1bkzc2EPrbHjV+GZyq3OK+1HVL/Cxu
A5mr6YVTtLceeAqpy3GL7a99BllU4RdK4fl4HgIX9lNIu7npMg3YeSmWKN7bBe6zPulZSZuLXdPt
Ftk1g5q/bk0yXDHmtTA7mFRtn9kcfSHv3i7wINRWsXUl2B98bSlYzgKuX3C2e4J7J27x9EQNe1Rt
nykpzKIX6Rsxf0L8Uc6/qxh4fplD7SGgqiLGOluOkdN6o8PxnSRFprMA97xbe9Pyip3JeBEsGSIv
N3XjvVku2A88Zv0RHbw+hP+zi+sZHrw+xg4hj5c5X4oTARkLriOZ+Sdu3uvxo0P9J3TzYa83Z/oq
1X/mP4tUBh64rW5l9SH/g6Q0qw6a5GkpJjLNTvrH/eEAG5dAP5K+OOkR//zOSUK+ATWeDKiF8q+D
R+EFudZJf0Tta8T2DoJ7PVLb2fk1F+nmBLB+1ZRCxDYt+LOTQKGwhor/5Bv6nxvzOJbguMLM7HBv
FQj94qcyAzUXPA4iWJkncrGoGiM5L1sWEupHpxTJtILtfTxhU1wnt4kh6weLReDlYbY56ZMy6DWC
TKaOggodUIg6ISvT+yxkiR/B9Zc8JZxU3VJC+FZPfEXv5Pzi5en7yxm24lMZR/FbYaa9DcTa8QP9
XubJGJvu5vLOwZVluuCB/fJZYWcTheioDFcD88hHc+ATX1dFV2UgN6s5PLguvmWoBCsEodcLIXkz
GYOfZxDfmYeKz9hcsCD2wtyHbA7k7y0RpHUtI4HvWWb3aeKriG0mERcoJMnmqeA3bCPz1NBiwYKB
PYJFQDOAKfBF3nCDhN+IdUmua96nVGwt479kDF+F5ClD7UUgrIcvKSGH+Laslnu9EjHLk2XKfSDQ
cWN0ck1s4sZs78OK8ArLJEyC7y6HoXlnBVSQ8liFnF4alQWnUL1BNc5AnaHISF0+JGFPMIBsfkgK
jICw9rNi8U/0u73QrlZ5hgcnHfNONb6Gqt/HYV4olfDdFrJ1iq9+Mlw79CKMzrvsNuDsv3D5QBda
RsUj4gnD2IkDISquGUcPUBK4MbNoNXBDiOUKDAxxFpRM0gFUKt4xBRrVDQfYmgNTFfkLWrAFHTx7
isuGJVSKIqsA9oyNoLtZ3uXdSg17HwDDg6OBubjvs1QobVVkE9+PAna4ApRBYBFsOReoD1C6+DXn
IZqDXsc1r+buF2/qDnrPgbieD8KKwEDmgDVxe3ACd3HmN3k0x1eXFuxUbWJvxtUNeFN6A87Zwfvv
wQi0XAohsdcqBUyZg0tAb9VmdAqamVgAa6wNaohAawoTIakFcg+2RXkMXoldiPY1uQzIA46byjuI
VVCwbVAcWgxxyRpqVbPzeoHej13Qy9ssyP4CmstSGuULjLnkhY2xbB8kADuzAWqEZHCMlBOi1HB+
Tg6X5nGMVvQtqE7vP6kOwnfzm0XBcgXBIeVq1bYXs/FG1Eaa5kmmW7WyUCkRcKaFIqOCl4GGYNXp
BcZvZeADz9sZYHQMlyUSdAxO1ancC9/s1H0KP4UsBeE93dAK/z6Uc3AZRBJMN8O6ioIM40Qklny+
yUDV7ForuUdqDRRSxtEztNY6IJWTG0EAWDuaTuFZ+hD2IgD2ILgJPF6LVBapEMWM2rHBTDktx6UE
C0lc9OgNMM+SmHSIsQnroQhsj2J5tgL9+v/H2UdU9gnmMb1+FfNQFSc0vwnCJT+GmmIQLBA1QPw0
3OCcBUv93uBAc0VL/gOtA8Oc+svXs0crgfjB+MC8HNJXDOmLiTvh5RTCpeZXL0FMd2VvcecBNlCV
OBSk3s4uJmz26vU1u3x99XoGIXp6+frimk0v3jHAtz9evGsz6MRmb6HXBfvw6u3lBZu+e3t2cX3d
aaz4mi4Go0OtCqgwA0n5HAOuQuHoHdpCE2VQ7YPWIZ/4GEioh4PnenQ4RUKAiEFECMPgQijqQx6m
PQtQIabPGLuZqVxCLEgDQmwVrou1zPbeYp5AiEDdO/c7oweYMgLMlQgPkYRWKfKq7anHlgKAU4lE
VWIOe0ZO9XwrQ0bqoZYaEN4cloLjyTDUsBeDzVat0spCVswYZsZAgI54TC9W17gAPJeD3z1vF4G/
4XjG83TyXCyAkpY0qlZch73VgV27OKAOmYd+yUkAeWIds4p3XMMsIdZBwsNeTwvJ9l5SVLiXAclZ
9OhSqkUqoyKR4lhz37E90TIqSGFs1/SFLQ5kO8N1AS3RRKmkrcDCZ/08SjQQ02DPtDvYru1zjj1M
b+KY2Cv4hivI3LCi+RaVQiaGfAbkb8GhlMqF0p/bUGJZgFIMSzhXxVK7MJzO+wZ7ImvU8SHtYJXl
rfL4Rmm2z3iCbUGUR5A28VgEK6oDtBvTdZFmoFImLgujQVoY990J4HhCzNBkDqLkHNLogTHRudQ3
mq6LKAcjmqaNXYtFoumYbpZABAIcDwo3YUQ6Bw4IdAAARH0BUxopaBL4so3ACgRHaMEqoWAYaVAL
UUyKXUuoCjrDk74FzU+R+ZS/uXEsMjTPRId8gFYrGWqAOMdzFoTPiVfAPeAtJmdQyNK1kLmrU8Vc
lFCRctWebZTiDobKFN/ZiZdt5vQte6GtaFonK1gxIR3jcAVBqcpE/OdrmbG2IXiOY6HR8NRhrwDK
geOcEDZjZ9P3bRgLHMxhEa0DH9ybUj5FxJK8Q+Qn7Mjg5QpJK1KM1bXDTn0IQCseLrpQV2pw7wtw
VzMRTMlw7wb9yVpuZQqzaFnlw8UdRiuEhzxs61CIE38IYiiuQCyILYKiFELg99N4WgDoqkzE2gAH
rSE5ulgjxoljLuulypVZdyr4TZQWRqBdGBb3Aws4BEBc+4uVPw+OB3rQ8w6bmjEhT5c0gJtq1XgH
TrhI+RJFAzuBTCoJCZFgCRoB57jaeYq2OwsD3AChkho/nSBUxq5m74lRBQKhzPM8oy9zkXmr2XS1
0DGRJspyBwdNiFd0el/M86V2eWkyK0N4ldLSN7AG6x5MUfgZgU55V6GOdDmwSjpBHCAbfbJn0UMH
gA88jTGrWyNxt8DkcaRiCEAMBXSBBqx6RhxWcAQWyNBxUv2pKAyF9MVTDItAuYAEOB3YNXaChWPa
qpIWwvp3rI+FlcGaWEGT/EX1rPSWgiiqatesrwmJZWpixboQj7McokB36en1AoxgUWI8yY11lCa1
nq0kFNa4OIsKTBSlNUVyn2ecKX5rkgVuDRWbX3irZJ+D4BD/BM+0UkEa/W2KAvVTnQgriMCXSgBq
mo9cefiEjkaCK12BOj2OiyWSt0XVjSmOdEdx2inu6OmsYqvY4bK2VWa0L6L9X3+DVm8oUVfj7Lky
+xL6ezo+bT3QEEcPmbAENHgbhITca4sXH5BBOjLkKKgQpgNZMYjgJyAAnxoMhglSQztUGO60YbvB
c4Uea80lWO6ZEK3hAH4hxJpsvw9xc8ssbTaAG/1tN0TmdZ5TDFfC5oIcCb9eQxtQZn+VCchaej40
n1YWbaNV+2t+kUVxWRPwp2eimrahY3mgzpQmGxTr2yjT1FYx6j5soox20au2M7l1N5Aq/NNI5jF9
eE3DGB0k0RWNbKgVZBL3a8Cp8SfhDrb3jkCINZQ8JxZ6l2AuNKm5WGBIox1egg+rYu3gcqF93xqa
0ZLjNIXkENcZb7KZ6A/zwFyl8usc9rayaD7GxovlC4yaocbImpMhhg7cPHFy/ZWiKs14iFa02XDb
z4pP5zTRHI+NKIrlqEUd6MAPIeFFzIjF9DZTAYtoiC0y23PANffYEupVVSml2scq9NK5rxgTAtc8
oHoWso2OyXPck0ny0Kxg8xtBAnUxeWWMs9FycBIdAXHBYVSbsKLcoCWo9+wmetnh9iKV1rpVgwtj
ITwAUGwBVdEcPdvBDz3WW8rYVGuF9BLEC1nZACKSox//Ff1WEk1BTHSSKIJ0JInVWMabCItDjPm4
S+upkmesds1tVt0m3imq8+UyFUuzb1juyCK6xm/w3TQEI95gmb49f4sfSDL5y2AGDAhroUsSTp9N
xAkVsV1yT00d61kBIJRS39oPySJNXYIJ9d1JmT9NAqxANrVKS2FQqcToE9YGXhtiUrLibWgG6RHR
ZAWUhby0ECkUJw5GlxhTqr5pErPeDOS17UDzuNFK2DlAdoA+FKCKUGDooan17WKGpm21iLZxAUmU
ecykaaSI3QtEibbEQIizEdQxY4qN7E5J3tyw6RdK/CQMMMFYm1O7v7WNVGzvZ0GmFVlsGK1MG0UE
LAhNzWFCAu60QynnE/IOFiUdqNdACo2/MMJYwInImeBXJHyOB9x1HQdInEdJaC4QOwF/xkSTwlZ0
C3wUt/Em7G8EZjh+BxUb/o4UqUoroYP9AIkkQHCdBr7ZRikewRH43JaBCOFQWlRUW1A5jh8aAUYN
ZrBYp1mJAfrF8FEdBnpKRtVsE/by8nQ2GXx71B4d3/Xbw7the/Bt/1sfUruOnvv4op6HcfNk3NNB
Vl8djJ5r+Kcf1li7GHodY7YA1ZrNRIJhtBsItvI2TH+hLU+LcFtUdWn5HIbCCtCB5OMRclaFrpzi
CRF4AMH9vZcUT2gm6l6jQS9cmJaPVotDoLNT7nrKxNQBENuUqYW9GyydFBV/oI55AGXLRu+QUD+U
lr40G+r8QItEi0jUAVSkZShutVviLhOxKg5WnEGytz9dhovWvgbTx0qFdlPi1YeoX4EjMax9AE1/
fa28nnsAMVd2Cz7si32e1trSTZJJOlGsP/rlmU8nVz3ytMbKL8qcjzik8xGLIKQv3FQdFlntw2xL
v3YV1W6uIBnpwxYoFOAwn94MqTpcTy/tS3J4X39lTp8Njeb6EafdK9qAfuhzcOYXG+FxlQE+XmEO
HmcY9Q56R/Dz2WvcJBwvBB8cLAbjg6MFPxr1j3u9/lwMj3ve8ZiLHvf4QgzHR+wZWSLOavqYrkij
A3Miu8pNHwlt0IcG9Vfx9IfppAruaqY1G5v08bp+5wi/yYcHVRZmc6pm9lUka/pTNJuqeZMynyjB
NxqC5TyIeboxDOKLGJm8ETEAmZrNNpyeuQ/MeerfgkSf9BzRJWkxqPr//vv/AvtVifA=
===END CRASH DUMP===

**Comment by Muqsit** [comment]
https://github.com/BlockHorizons/BlockPets/issues/147

**Comment by Flucid** [comment]
That didn't help at all, as I don't use PureEntitiesX. Also It doesn't happen when I spawn in a mob it just happens when I start the server it automatically crashes.

**Comment by Muqsit** [comment]
@Flucid if you would have read the issue correctly, you would have figured out that it has nothing to do with PureEntitiesX. The issue arises in the parameters passed to `Entity::createEntity()`. Maybe thoroughly read the discussion before coming to a conclusion next time.
```
#4 plugins/TeaSpoon_dev-265.phar/src/CortexPE/tile/MobSpawner(90): pocketmine\entity\Entity::createEntity(integer 12, pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
```
