### ISSUE TITLE
getServer() non null after 2 pets fight 2 times and respawn.

### ISSUE THREAD

**Issue by kabluinc** [BlockHorizons/BlockPets#19]
Ok I'm getting this very weird issue. This is how to reproduce it everytime. 

2 pet owners spawn their pets. Then they hit each other and move away so the 2 pets start fighting each other. one dies and respawns. Then you hit each other again, pets fight again however after a pet dies this time, all pets freeze and loads of plugins start spamming console with getServer() on null.

The pet plugin spams the error could not tick level world. getServer() on null in line 100 of basepet.

These errors keep spamming until the server is restarted and if the above is repeated (2 pets fight and die twice, the plugin bugs out)

**Comment by Sandertv** [comment]
I've actually come by this too, but didn't manage to get the exact error. I'll look into it. :) It would also be apprciated if you could paste the full error. It might not be needed, but could speed it up a bit.

**Comment by Sandertv** [comment]
Okay I think I found what causes it. I'll push a commit shortly.

**Comment by kabluinc** [comment]
This is the exact error if needed.

`2017-06-11 [03:23:06] [Server thread/CRITICAL]: Could not tick level "world": Call to a member function getServer() on null
2017-06-11 [03:23:06] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/plugins/BlockPets-master/src/BlockHorizons/BlockPets/pets/BasePet" at line 100`

**Comment by Sandertv** [comment]
I hope the referenced commit fixes this issue. If it didn't please don't hesitate to say so.

**Comment by kabluinc** [comment]
Thanks :) I will try now

**Comment by kabluinc** [comment]
The error in basepets.php is fixed. However still every now and again this error happens where all my plugins start displaying getServer() on null. when this happens, the pets freeze. Hitting the other players pet sometimes restarts the fight and it all works again. 

This is the error from one of the plugins.

`[12:54:28] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'HungerGames vbuild#06': Call to a member function getServer() on null on xbeastmode\hg\Events
[12:54:28] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 69'

**Comment by Sandertv** [comment]
Alright, I'll look into it!

**Comment by Sandertv** [comment]
I'm quite confident the latest commit has fixed your issue. Please try again. :)

**Comment by kabluinc** [comment]
Your so fast XD

**Comment by Sandertv** [comment]
😄

**Comment by Sandertv** [comment]
I believe it's important to fix bugs for people. I'm just very glad you're so cooperative with reporting those. I don't have all the ways to test them, so I'm very happy you can.

**Comment by Driesboy** [comment]
no need to learn for exams @Sandertv ?
