### ISSUE TITLE
Crash data when pet dies 

### ISSUE THREAD

**Issue by servantthought** [BlockHorizons/BlockPets#190]
02.02 18:25:11 [Server] Server thread/CRITICAL Error: "Call to a member function getServer() on null" (EXCEPTION) in "src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 72
02.02 18:25:11 [Server] Server thread/DEBUG #0 src/pocketmine/entity/Living(581): pocketmine\event\entity\EntityDamageByEntityEvent->getDamager()
02.02 18:25:11 [Server] Server thread/DEBUG #1 plugins/BlockPets (2).phar/src/BlockHorizons/BlockPets/pets/BasePet(337): pocketmine\entity\Living->attack(pocketmine\event\entity\EntityDamageByEntityEvent object)
02.02 18:25:11 [Server] Server thread/DEBUG #2 plugins/BlockPets (2).phar/src/BlockHorizons/BlockPets/pets/IrasciblePet(72): BlockHorizons\BlockPets\pets\BasePet->attack(pocketmine\event\entity\EntityDamageByEntityEvent object)
02.02 18:25:11 [Server] Server thread/DEBUG #3 src/pocketmine/Player(2566): BlockHorizons\BlockPets\pets\IrasciblePet->attack(pocketmine\event\entity\EntityDamageByEntityEvent object)
02.02 18:25:11 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(148): pocketmine\Player->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
02.02 18:25:11 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(156): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
02.02 18:25:11 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(108): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
02.02 18:25:11 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/protocol/BatchPacket(119): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
02.02 18:25:11 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(108): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
02.02 18:25:11 [Server] Server thread/DEBUG #9 src/pocketmine/Player(3110): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
02.02 18:25:11 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(170): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
02.02 18:25:11 [Server] Server thread/DEBUG #11 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 174.208.11.8 4470, raklib\protocol\EncapsulatedPacket object, integer 0)
02.02 18:25:11 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(110): raklib\server\ServerHandler->handlePacket()
02.02 18:25:11 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(100): pocketmine\network\mcpe\RakLibInterface->process()
02.02 18:25:11 [Server] Server thread/DEBUG #14 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
02.02 18:25:11 [Server] Server thread/DEBUG #15 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
02.02 18:25:11 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2349): pocketmine\snooze\SleeperHandler->sleepUntil(double 1549131911.8938)
02.02 18:25:11 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2209): pocketmine\Server->tickProcessor()
02.02 18:25:11 [Server] Server thread/DEBUG #18 src/pocketmine/Server(1785): pocketmine\Server->start()
02.02 18:25:11 [Server] Server thread/DEBUG #19 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
02.02 18:25:11 [Server] Server thread/DEBUG #20 (1): require(string phar:///custom.phar/src/pocketmine/PocketMine.php)

**Comment by thehexmor** [comment]
my problem too . update you plugin plz

**Comment by Ifera** [comment]
Should be fixed with the latest update. If not then please do make a new issue.
