### ISSUE TITLE
SQL Prepare Error

### ISSUE THREAD

**Issue by LegoFan48737** [BlockHorizons/BlockPets#202]
`2019-04-28 [23:29:54] [Server thread/ERROR]: [BlockPets] SQL PREPARE error: duplicate column name: Visible, for query ALTER TABLE Pets ADD COLUMN Visible BOOL NOT NULL DEFAULT TRUE; | []`

Using latest dev build from poggit

**Comment by Muqsit** [comment]
Duplicate of #188
