### ISSUE TITLE
An Error from MySQL

### ISSUE THREAD

**Issue by BlackPMFury** [BlockHorizons/BlockPets#211]
Src: BlockHorizons\BlockPets\Pets\datastorges\SQLDataStoreger
Errror: [Server thread/CRITICAL]: Error: "Class 'poggit\libasynql\libasynql' not found" (EXCEPTION) in "plugins/BlockPets-master/src/BlockHorizons/BlockPets/pets/datastorage/SQLDataStorer" at line 141

Content: I dont know how to fix that and I need you help that

**Comment by Adam1609** [comment]
enable the mysql at php.ini

**Comment by lukeeey** [comment]
You must download the plugin from poggit.
