### ISSUE TITLE
error spam in console

### ISSUE THREAD

**Issue by optimusprime338** [BlockHorizons/BlockPets#22]
11.06 11:58:49 [Server] Server thread/CRITICAL Error: "Call to a member function getId() on null" (EXCEPTION) in "/BlockPets (1).phar/src/BlockHorizons/BlockPets/pets/IrasciblePet" at line 76
using latest PMMP

**Comment by Sandertv** [comment]
That code no longer exists. Please get the latest version of the plugin and try again.
