### ISSUE TITLE
Known Issue

### ISSUE THREAD

**Issue by ghost** [BlockHorizons/BlockPets#222]
• BlockPets will be broken if there is a PureEntitiesX plugin on the server, crash: https://crash.pmmp.io/view/4920174
• Feeding the pet doesn't work like an issue #173
• When the pet dies from drowning, crash: https://crash.pmmp.io/view/4920769

**Comment by BlackFire4775** [comment]
Swimming Pets Drown ^

**Comment by Ifera** [comment]
Should be fixed with the latest update. If not then please do make a new issue.
