### ISSUE TITLE
How can i Prevent pets from Clearlag

### ISSUE THREAD

**Issue by galaxytwenty** [BlockHorizons/BlockPets#232]
When clearlag is running the pet will be removed.
toggle(on) dont work, only left and rejoin bring the pet back.

How can i Prevent the Pets from clearlag ?.

Best greeetz

**Comment by edwinyoo44** [comment]
```
use BlockHorizons\BlockPets\pets\BasePet;



if( !($entity instanceof BasePet) ) {

some code......

}
```

**Comment by galaxytwenty** [comment]
did you know AutoClearLag?.

what can i change to make this ?,. the part of exempt Entities looks like

  $clear = $config["clear"] ?? [];
        $this->clearItems = (bool) ($clear["items"] ?? false);
        $this->clearMobs = (bool) ($clear["mobs"] ?? false);
        if(!is_array($clear["exempt"] ?? [])){
            $this->getLogger()->error("Config error: clear.exempt attribute must an array");
            $this->getServer()->getPluginManager()->disablePlugin($this);

            return;
        }
        
        Thanks for Answer and Help.


Best greeetz

**Comment by edwinyoo44** [comment]
In line 103, add a new criterion
https://github.com/TwistedAsylumMC/AutoClearLagg/blob/1db862e3fbe225b73c378be4a5bff91b5084b0d4/src/twisted/autoclearlagg/AutoClearLagg.php#L103

**Comment by galaxytwenty** [comment]
okay nice. Thanks.
another question i have error when pet die,
when fall from high place or when die in lava or void,

can u say me how to fix.

thanks for the quick answer

**Comment by edwinyoo44** [comment]
Just turn on Invulnerable-Pets in config

**Comment by galaxytwenty** [comment]
yeah, sure, but then the Pet don´t take damage, and i like this function.

can u fix this ?

Best Greetz

**Comment by MrNinja008** [comment]
> When clearlag is running the pet will be removed.
> toggle(on) dont work, only left and rejoin bring the pet back.
> 
> How can i Prevent the Pets from clearlag ?.
> 
> Best greeetz

Easy Just go in Autoclearlag config and
# config 
# Entities to clear
clear:
  items: true
  mobs: true
  exempt: # Array of entities not to clear
    - Zombie
    - Pig
    - WitherPet like this
You can get the pets name by seeing thier php namespace

**Comment by edwinyoo44** [comment]
> yeah, sure, but then the Pet don´t take damage, and i like this function.
> 
> can u fix this ?
> 
> Best Greetz

This problem is a little troublesome, I am currently trying to repair this plug-in

**Comment by galaxytwenty** [comment]
@MrNinja008

Im fine with 
}else if($this->clearMobs && $entity instanceof Creature && !$entity instanceof Human && !$entity instanceof BasePet){

THX

**Comment by galaxytwenty** [comment]
Yes, I think it would be a possibility to define all the causes individually?

cause_firetick
cause_fire
Cause_fall
and so on.

Best Greetz

**Comment by edwinyoo44** [comment]
> > When clearlag is running the pet will be removed.
> > toggle(on) dont work, only left and rejoin bring the pet back.
> > How can i Prevent the Pets from clearlag ?.
> > Best greeetz
> 
> Easy Just go in Autoclearlag config and
> 
> # config
> # Entities to clear
> clear:
> items: true
> mobs: true
> exempt: # Array of entities not to clear
> - Zombie
> - Pig
> - WitherPet like this
> You can get the pets name by seeing thier php namespace

This is also a good solution, but he needs to add all the pet category names

**Comment by galaxytwenty** [comment]
Hey @edwinyoo44 

can you say me how to change the Xp Points when feeding Pets ?,
i mean per bread 1% of 100%

thanks in advance

**Comment by edwinyoo44** [comment]
> Hey @edwinyoo44
> 
> can you say me how to change the Xp Points when feeding Pets ?,
> i mean per bread 1% of 100%
> 
> thanks in advance

See here
https://github.com/edwinyoo44/BlockPets/blob/4416b37f4fcce584a050048385f52593bc1b9681/src/BlockHorizons/BlockPets/pets/BasePet.php#L311

**Comment by galaxytwenty** [comment]
i have found this, but with a int over 100 nothing happends.

maybe you can say me how to make it working.
to make that 1 bread give 1%

or how change the 40 ?

Thanks in advance

**Comment by edwinyoo44** [comment]
> i have found this, but with a int over 100 nothing happends.
> 
> maybe you can say me how to make it working.
> to make that 1 bread give 1%
> 
> or how change the 40 ?
> 
> Thanks in advance

Try to change 40 to 4.

**Comment by galaxytwenty** [comment]
With 4 ist one Level per Bread, lol

i mean 100 Breads per level

but 400 dont work

**Comment by edwinyoo44** [comment]
> With 4 ist one Level per Bread, lol
> 
> i mean 100 Breads per level
> 
> but 400 dont work

This is a math problem, I am not good at it. XD

**Comment by edwinyoo44** [comment]
Maybe you can try change this line

https://github.com/edwinyoo44/BlockPets/blob/4416b37f4fcce584a050048385f52593bc1b9681/src/BlockHorizons/BlockPets/pets/BasePet.php#L311

to 

`

if($hand instanceof Bread) { //I'm not sure this line.
    $this->addPetLevelPoints((int) (LevelCalculator::getRequiredLevelPoints($this->getPetLevel()) /100 ));
} else {
    $this->addPetLevelPoints((int) ($nutrition / 40 * LevelCalculator::getRequiredLevelPoints($this->getPetLevel())));
}

`

**Comment by galaxytwenty** [comment]
no, i have found one solution,

have change in BasePet from 40 to 400

and in  LevelCalculator

from: return (int) (20 + $level / 1.5 * $level);
to: return (int) (200 + $level / 15 * $level);

This works Fine.

Thanks man for quick Answer.

what about the die Bug? have you found a solution ?

Best Greeetz

**Comment by galaxytwenty** [comment]
and other question, How to save the PetSize on Database ?. i have pet size per level, but in databas noting change.
when rejoin pet is back to normal size

**Comment by galaxytwenty** [comment]
hey sry for a lot of question,

but why horses dont move when ridding ?.
all of the other entity move´s when ridding.

Best Greetz
