### ISSUE TITLE
DO YOU CREATE PURPOSE BUGS?

### ISSUE THREAD

**Issue by MadooxMc** [BlockHorizons/BlockPets#238]
I try to share crash problem, but anyone answer me.

**Comment by lukeeey** [comment]
Everyone has their own lives, and currently i’m the only one maintaining this. I saw your issue but i didn’t have time to look at it properly and i will look when i can.

**Comment by lukeeey** [comment]
if you make one more useless issue i will block you from this organization.

**Comment by MadooxMc** [comment]
ok sorry i didn't mean to offend you, and please don't block me i just want to report the bugs i find because this plugin is magic
