### ISSUE TITLE
Pets duping and not resetting.

### ISSUE THREAD

**Issue by kabluinc** [BlockHorizons/BlockPets#24]
Hi,

For some reason pets are duping like crazy on my server. Almost everyone has like 5 of the same pets. After relog it goes back to 1 but few mins later it starts duping again. Server starts to lag as a result.

Also I tried deleting the database file as some players used creative to feed pets which made them huge and started to lag the server.  However after server starts and the database file is recreated, everyone still have their pets, same level etc. 

Please help :P

**Comment by Sandertv** [comment]
Whoops, I think the duplicating issue is actually resolved in one of the latest issue. It was due to the pets not being removed when they'd die, causing them to remain registered in the database and keeping duplicating. That should hopefully be fixed now. I'm adding an option to make feeding give experience ASAP.

**Comment by Sandertv** [comment]
This here should have fixed your first issue: 25a1aefd7a344e2c550d8becc9747d3be424fba4

**Comment by kabluinc** [comment]
Thanks. And do you have any idea how I can completely reset the pet plugin? deleting the database file doesn't make any difference. everyone retains their pets, same level

**Comment by Sandertv** [comment]
For your issue with the database removing not removing all pets, please try setting Fetch-From-Database to true, and wait a bit for the owners of the pets to quit and join. After that the settings from the Database should go in effect. If the option Fetch-From-Database is set to false, it will only store the pets in the database, just in case the pets somehow dissapear and you need a backup. Alternatively, you could remove the plugin, restart, load the world by teleporting to it, then upload the plugin again and restart once again.

**Comment by kabluinc** [comment]
Okay many thanks

**Comment by Sandertv** [comment]
No problem, hope my solutions work! Make sure to generate a new configuration file to use the new config option, otherwise it'll come up with an error :P

**Comment by Sandertv** [comment]
I added a config setting in the commit above to simplify what I said a lot. In future occasions, you can just set `Hard-Reset: false` to true, and restart the server. It will then automatically switch Hard-Reset off again for the next restart and reset all data. For convenience, it sets Fetch-From-Database to true, so not only the pets of the players that joined between those two restarts will get cleared, but the pets of future players too.

**Comment by kabluinc** [comment]
Thanks! That will make this much easier.

One thing iv seen tho, it seems the getServer() on null is back.. The error below is shown when pets are attacking

`2017-06-13 [22:14:56] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\entity\EntityDeathEvent' to 'BlockPets v0.1.0': Call to a member function getServer() on null on BlockHorizons\BlockPets\listeners\EventListener
2017-06-13 [22:14:56] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/BlockPets-master/src/BlockHorizons/BlockPets/pets/BasePet" at line 153
2017-06-13 [22:14:56] [Server thread/CRITICAL]: Could not tick level "faction": Call to a member function getServer() on null
2017-06-13 [22:14:56] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 67`

Sorry for the trouble

**Comment by Sandertv** [comment]
Oh yikes, pets are attacking again while they're already closed.... Hmmm...

**Comment by Sandertv** [comment]
Okay I HOPE the commit above fixes this.

**Comment by kabluinc** [comment]
Still shows this error ;-;

`2017-06-13 [23:09:39] [Server thread/CRITICAL]: Could not tick level "world": Call to a member function getServer() on null
2017-06-13 [23:09:39] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/BlockPets-master/src/BlockHorizons/BlockPets/pets/BasePet" at line 122`

**Comment by Sandertv** [comment]
Made another attempt in the latest commit, please try again.

**Comment by TDMidkwhatisxd** [comment]
still not fixed on latest

**Comment by Sandertv** [comment]
@TDMidkwhatisxd it does not sound like you ARE using the latest commit. I've tested it and this particular error does no longer show up.

**Comment by kabluinc** [comment]
The getServer() issue still persists on line 122 of BasePet

**Comment by kabluinc** [comment]
![image](https://user-images.githubusercontent.com/17614796/27141600-8dba92d4-5120-11e7-8085-b466556d1f9f.png)

All the owners pets are staying in the world even though they aren't online, and not despawning either..
