### ISSUE TITLE
Ender Dragon Pet

### ISSUE THREAD

**Issue by Seathic** [BlockHorizons/BlockPets#247]
I found a bug on the pet ender dragon, namely the movement bug on the dragon facing upside down, the dragon's tail is in front when the player is moving & the dragon's head is behind, fix this

**Comment by NgLamVN** [comment]
> I found a bug on the pet ender dragon, namely the movement bug on the dragon facing upside down, the dragon's tail is in front when the player is moving & the dragon's head is behind, fix this

Fixed in #245...

**Comment by Ifera** [comment]
I don't have time to test this right now but let me know if the latest dev build fixes this issue.

**Comment by Ifera** [comment]
Issue has been fixed.
