### ISSUE TITLE
Umm, Just An Ask

### ISSUE THREAD

**Issue by zhorifcraft451-pm-pl** [BlockHorizons/BlockPets#256]
Can I sell the modified plugin of this plugin, bcs i want to modify this blockpets and adding some feature and sell it, so can i sell the edited Plugin??

**Comment by Sandertv** [comment]
The plugin uses the Apache licence so yes, that is allowed under the terms of the licence.

**Comment by ZhorifCraft451** [comment]
so i can sell the modified(modify by me) right?

**Comment by Sandertv** [comment]
Yes, so long as the original LICENSE including copyright notice is left in place, as described in the licence.

Brief summary of the licence:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/16114089/178150373-00b58685-0252-41b8-9caf-b4559b079a4e.png">

**Comment by ZhorifCraft451** [comment]
okay, thank you
