### ISSUE TITLE
pets not respawning

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [BlockHorizons/BlockPets#27]
Pets does not respawning after relogin. I even used toggle all, on and off. I think, maybe pets don't save?

**Comment by Sandertv** [comment]
Any errors when players quit or join?

**Comment by TDMidkwhatisxd** [comment]
Imma test now again to see.
Mcpe windows10 have a bug in servers were, it use 100% of ram and pc freeze, so I cant test for too long xd ( 4gb ram)

**Comment by TDMidkwhatisxd** [comment]
just a question, on relogin pet should respawn and toggle is to turn respawn off and on?

**Comment by TDMidkwhatisxd** [comment]
[Server thread/CRITICAL]: Could not tick level "SpawnMap": Call to a member function getServer() on null
[09:30:30] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 69

**Comment by TDMidkwhatisxd** [comment]
Tested again. On relogin I toggle pet on, it spawn but is invisible. How I know?
If a pet attack me , the other pet keep taking damage and my pet lvl up, but , my invisible pet don't attack other players. Tested in 1vs1 arena, it don't attack players.

**Comment by TDMidkwhatisxd** [comment]
I see , not many report this error. Not all use pmmp? If so, what server software is compatible with this plugin?

**Comment by Sandertv** [comment]
You shouldn't have to toggle your pet on/off.

**Comment by Sandertv** [comment]
I'm actually using pmmp myself and it works perfectly fine. I'm suspecting something in the latest PMMP commits messed it up.

**Comment by TDMidkwhatisxd** [comment]
then it is turned off auto? because wen I toggle my pet, it say is toggled on

**Comment by Sandertv** [comment]
That's a bug. I accidentally made the message reversed.

**Comment by TDMidkwhatisxd** [comment]
plugin interfere with, SAC and SimpleAuthHelper, 

39] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'SimpleAuthHelper v2.0.5': Call to a member function getServer() on null on aliuly\helper\EventListener
[09:46:39] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 69
[09:46:39] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'SAC v3.2.5': Call to a member function getServer() on null on DarkWav\SAC\EventListener
[09:46:39] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 69

**Comment by TDMidkwhatisxd** [comment]
even so, pet does not respawn xd

**Comment by Sandertv** [comment]
Could you please turn Fetch-From-Database on in your config.yml. I'll see if I can reproduce this myself later.

**Comment by TDMidkwhatisxd** [comment]
and about console errors?

**Comment by Sandertv** [comment]
Did you already try the commit I mentioned above?

**Comment by TDMidkwhatisxd** [comment]
the commit may fix errors? I saw just typo fix for spawn. xd

**Comment by Sandertv** [comment]
Look closer.

**Comment by TDMidkwhatisxd** [comment]
ya :). imma test now. I already warned my players about test. To stop rage xd (too many restarts annoy them)

**Comment by TDMidkwhatisxd** [comment]
[Server thread/CRITICAL]: Could not tick level "SpawnMap": Call to a member function getServer() on null
[10:00:01] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 69

**Comment by TDMidkwhatisxd** [comment]
how to fix this? Maybe server see pets as players? :/

**Comment by Sandertv** [comment]
Could you please find out when this happens?

**Comment by Sandertv** [comment]
Found the issue, sorry for the inconvenience.

**Comment by TDMidkwhatisxd** [comment]
pet still don't respawn after relogin. Imma test again

**Comment by TDMidkwhatisxd** [comment]
well, it would be great if you can fix it. Players are so excited about this plugin xd. They say, "Pockemoooon"

**Comment by Sandertv** [comment]
Okay I pray the latest commit has fixed it. Please try again.

**Comment by TDMidkwhatisxd** [comment]
sorry, pet  is spawning. Maybe these errors stop them from spawning. xd

**Comment by Sandertv** [comment]
That could very well be. Try the latest commit. If that doesn't work, I recommed you to turn Fetch-From-Database in the config.yml on. (I would recommend that anyways)

**Comment by TDMidkwhatisxd** [comment]
Okay, yay.

**Comment by TDMidkwhatisxd** [comment]
already and still error. But pet spawned xd

**Comment by TDMidkwhatisxd** [comment]
now imma test

**Comment by TDMidkwhatisxd** [comment]
[Server thread/CRITICAL]: Could not tick level "SpawnMap": Call to a member function getServer() on null
[10:20:55] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 69

:(

**Comment by Sandertv** [comment]
Do you know if this happens if a pet gets damaged, or the pet damages someone else?

**Comment by TDMidkwhatisxd** [comment]
too many players :d

**Comment by TDMidkwhatisxd** [comment]
what if pet damage pet?

**Comment by Sandertv** [comment]
That comment made a light shine in my head. The latest commit MIGHT have actually fixed it. You'll have to try it out.

**Comment by TDMidkwhatisxd** [comment]
okay :)

**Comment by TDMidkwhatisxd** [comment]
[Server thread/CRITICAL]: Could not tick level "SpawnMap": Call to a member function addEntityMovement() on null
[11:18:54] [Server thread/CRITICAL]: Error: "Call to a member function addEntityMovement() on null" (EXCEPTION) in "/src/pocketmine/entity/Entity__64bit" at line 1208
[11:18:57] [Server thread/CRITICAL]: Could not tick level "SpawnMap": Call to a member function addEntityMovement() on null
[11:18:57] [Server thread/CRITICAL]: Error: "Call to a member function addEntityMovement() on null" (EXCEPTION) in "/src/pocketmine/entity/Entity__64bit" at line 1208
----
[11:21:23] [RakLibServer thread/NOTICE]: Blocked 39.54.90.254 for 5 seconds
[11:21:23] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 69
[11:21:23] [RakLibServer thread/NOTICE]: Blocked 1.32.75.182 for 5 seconds
[11:21:24] [Server thread/INFO]: [1vs1] [1vs1] - There is actually 1 players in the queue
[11:21:24] [Server thread/CRITICAL]: Error: "Call to a member function getServer() o
----
UMMMM..... ;-;

**Comment by TDMidkwhatisxd** [comment]
and if I attack pet, pet wont hit me back.

**Comment by TDMidkwhatisxd** [comment]
maybe @dktapps can tell us, wtf is wrong with pmmp ?

**Comment by Sandertv** [comment]
No, this is not PMMP. I can confirm this one, looking into it.

**Comment by TDMidkwhatisxd** [comment]
okay ^^

**Comment by TDMidkwhatisxd** [comment]
[Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 69
[15:15:58] [RakLibServer thread/NOTICE]: Blocked 71.167.183.94 for 5 seconds

everytime it gets this error, raklib block a ip. Why?

**Comment by TDMidkwhatisxd** [comment]
[Server thread/CRITICAL]: Could not tick level "SpawnMap": Call to a member function isAlive() on null
[15:17:13] [Server thread/CRITICAL]: Error: "Call to a member function isAlive() on null" (EXCEPTION) in "/BlockPets (5).phar/src/BlockHorizons/BlockPets/pets/WalkingPet" at line 117

and this :(

**Comment by TDMidkwhatisxd** [comment]
I just wanna normal pets, maybe if there is no pvp, maybe bye errors.

**Comment by Sandertv** [comment]
Then disable it in the config.yml.

**Comment by TDMidkwhatisxd** [comment]
[Server thread/CRITICAL]: Could not tick level "world": Call to a member function getServer() on null
[15:26:54] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/BlockPets (5).phar/src/BlockHorizons/BlockPets/pets/BasePet" at line 122

still error :(

**Comment by Sandertv** [comment]
Could you PLEASE stop just typing the error and find out when it happens? I can't magically fix it if I don't know when it occures.

**Comment by TDMidkwhatisxd** [comment]
well, I'm trying to figure out. But console just spams

**Comment by TDMidkwhatisxd** [comment]
I get same errors I reported here, even if pvp is off :( . I'm out of ideeas.

**Comment by TDMidkwhatisxd** [comment]
btw , server just froze.

**Comment by TDMidkwhatisxd** [comment]
well, is a nice plugin, but not stable.

**Comment by TDMidkwhatisxd** [comment]
there is a problem. You should not let players choose size for pets :(. A player did size 500, and bye server.

**Comment by TDMidkwhatisxd** [comment]
I will use TapToDO with pets to avoid that xd

**Comment by Sandertv** [comment]
You don't have to have players selecting sizes themselves. You can simply do `/spawnpet \<petType\> select \<size\> false \<player\>`

**Comment by kabluinc** [comment]
Pets not respawning after reclogging is happening to me too. If I select fetch from database to false, after relogs, the pet stays in the same place as before logout and stays frozen. If fetch from database is true, pet simply does not save.

**Comment by Sandertv** [comment]
Hmmm... Is there any errors using the latest commit?

**Comment by kabluinc** [comment]
Nope. no errors

**Comment by BrianZP** [comment]
yea no error. but confirmed. pet respawing after login is not working as intended

**Comment by Sandertv** [comment]
Okay looking into it right now. Please hang on.

**Comment by Sandertv** [comment]
Found out why Fetch From Database isn't working. Fixing it in a couple minutes.

**Comment by TDMidkwhatisxd** [comment]
but players can still select size of pets, how I disable that?

**Comment by Sandertv** [comment]
There's a limit you can select now in the config.yml. As I said above you can also do `/spawnpet ocelot select 1 false <player>` for players to get the pet and select the name themselves.

**Comment by TDMidkwhatisxd** [comment]
yes, but I wanna players to select a pet themselfes. and nice limit xd

**Comment by Sandertv** [comment]
I'll add a size limit exceed permission so you could set the limit to 1 and allow yourself to make bigger ones.
