### ISSUE TITLE
poggit

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [BlockHorizons/BlockPets#29]
I need latest phar.
I cant unphar or phar online, I receive errors on pc (php errors on page).
And poggit dont wanna make more phars.

**Comment by Sandertv** [comment]
Apologies, but don't blame me for this. @SOF3 could you ask @Intyre to fix that stuff?

**Comment by TDMidkwhatisxd** [comment]
as expected from dktappsteam  :))))))

**Comment by SOF3** [comment]
Fixed.

**Comment by Sandertv** [comment]
Thanks @SOF3
