### ISSUE TITLE
Enhancement: Higly Customizable Pet Stats

### ISSUE THREAD

**Issue by kabluinc** [BlockHorizons/BlockPets#30]
Hi, There is another glitch which makes it possible for people in survival mode to fly using pets. Riding a vex or bat pet, looking up at the sky while moving forward makes the player fly upwards.

I dont know if this was an intended feature. However this may be an issue for survival servers.

**Comment by Sandertv** [comment]
Yeah this was indeed an intended feature. Flying pets like ghasts, ender dragons, vexes, withers, blazes, bats and other flying pets all share that behaviour. Pets have a very low 'flying height' though, which makes it impossible to fly very high.

**Comment by Sandertv** [comment]
I'm leaving this open for myself to think of a way to allow managing the different types of pets better. Perhaps permission nodes of swimming pets, walking pets, bouncing pets and flying pets, or something in that fashion.

**Comment by TDMidkwhatisxd** [comment]
fly pets are awesome. Why a issue? xD

**Comment by LordJoshie** [comment]
yah, flying pets is epic. 

perhaps just a toggle in a config for each pet type, to control it's allowed behavior. 

for each pet, allow whether it can be ridden, flown, storage, w.e.. 

then you can modify/customize the use of the plugin a lot more, for like... higher tier pets, with more capabilities. 

like maybe a main class of basic pets, then rideable pets, then rideable pets with inventories, then rideable pets with inventories that fight for you :P 

I like the concept of tiered pets with more capabilities as the pets get more intense. 

maybe add tiers at higher levels, so once pet reaches lvl 10, it goes to tier 2 lvl 1 and gets a new skill ? 

so many possibilities ! this plugin is awesome tho :P

**Comment by Sandertv** [comment]
I changed the title to fit my plans a bit more. Every pet will have highly customizable properties, like speed for every pet, and for example jumping height for bouncing pets, swimming speed for swimming pets, flying height for flying pets etc. Also pet tiers will be revamped to be actually useful.

**Comment by LordJoshie** [comment]
Sander, ily bro :) Hehe.
NoHomo

**Comment by Sandertv** [comment]
8bd47fbe2ca7dae4024b3f33d7fe9d73d29846a1
