### ISSUE TITLE
Pet removing does not have the expected behaviour

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [BlockHorizons/BlockPets#35]
Cant ride pets, and /removepet don't despawn the pet.
Wen I ride pet, it just froze, it don't even follow u anymore.

**Comment by Sandertv** [comment]
What exactly do you mean with freezing? Does your game freeze, or does the pet not move anymore? Does /removepet say it succeeded but didn't do anything?

**Comment by Sandertv** [comment]
Pet riding works perfectly fine with the latest commit. Note that llamas, horses (and related) and pigs freeze your game though. The removepet issue, yes, I see that.

**Comment by TDMidkwhatisxd** [comment]
wtf? wen I ride pets with latest com, the pet wont move at all. I mean I don't even ride it, it just get stuck.
Should I delete config?

**Comment by TDMidkwhatisxd** [comment]
And game freeze, happens without pet plugin. Client have leaks, used 4gb ram, and froze. Tested on clean server.

**Comment by Sandertv** [comment]
The pet got stuck when (trying) to remove the pet.

**Comment by TDMidkwhatisxd** [comment]
pet got stuck wen trying to ride it. Wen I use saddle, nothing happens , just pet get stuck. On pigs saddle show on the back, but still nothing happens.

**Comment by TDMidkwhatisxd** [comment]
and removepet, didn't remove pets but lagg clearall command removed it.

**Comment by Sandertv** [comment]
Lagg clearall command removed it? That isn't supposed to be possible lol.

**Comment by TDMidkwhatisxd** [comment]
well, it is :)

**Comment by TDMidkwhatisxd** [comment]
I mean, after I did removepet, I did clearall. So pet was removed, but entity not.

**Comment by Sandertv** [comment]
Found out why it wouldn't remove. Fixing in a sec.
