### ISSUE TITLE
Compatibility Request

### ISSUE THREAD

**Issue by LordJoshie** [BlockHorizons/BlockPets#37]
I'm using a software that still uses old protocol methods/paths. 

So when using this plugin I get the following error. 

In short  

Error: Class pocketmine\network\mcpe\protocol\AddEntityPacket not found

I'm simply asking there to be an alternative branch called 'OldProtocol' or something to provide compatibility with other softwares. 

Thanks!

**Comment by Sandertv** [comment]
At the moment I'm not really into supporting third party softwares of PocketMine, especially not with Entity related plugins like this one. If the third party software you're using doesn't keep up with the packet locations, it will definitely not keep up with other hugely breaking API changes in PocketMine. 😞

**Comment by LordJoshie** [comment]
I really think you should....

but ill edit your version, no worries.
