### ISSUE TITLE
EnderDragon 

### ISSUE THREAD

**Issue by MCNationPE** [BlockHorizons/BlockPets#38]
when i spawn enderdragon the dragon is dead

**Comment by Sandertv** [comment]
Please provider more information so I can help you. On my server everything works perfectly fine. Are you using win10?

**Comment by MCNationPE** [comment]
yes i use win10

**Comment by TDMidkwhatisxd** [comment]
enderdragon is really dead :) . It gives dead animation. So , after that he become invisible pet.

**Comment by Sandertv** [comment]
This is a Win10 edition only bug. Blame Mojang.

**Comment by MCNationPE** [comment]
but why i can see ender dragon on lbsg?

**Comment by Driesboy** [comment]
LBSG is using steadfast2
and i checked it @Sandertv and it works clearly on ios

**Comment by Sandertv** [comment]
It shows the enderdragon perfectly fine for me too. I don't see why the enderdragon would be dead...

**Comment by Driesboy** [comment]
Its only on windows 10

Op 26-jun.-2017 07:42 schreef "Sandertv" <notifications@github.com>:
