### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by TheDiamondYT1** [BlockHorizons/BlockPets#43]
It would be nice to include configurable messages, just like [this](https://github.com/TheDiamondYT1/PocketPerms/blob/master/resources/lang/en.json), however you'd probably prefer to use YAML since it's simpler for users to edit. Meh.

If needed i can contribute to alot of this.

**Comment by Sandertv** [comment]
Json is perfectly fine by the way, I don't really have a big preference of one above another.

**Comment by TheDiamondYT1** [comment]
I was just saying yaml since it goes with the config and pets config. I use json in my plugins since I don't intend for the messages to be edited. I'll use YAML to match the other BlockHorizons plugins.

Also would you rather I have a class for getting the messages like the BlockPetConfig class or just add a translate method to the main class which accepts a string

**Comment by Sandertv** [comment]
I'd prefer a new messages class, but if you really want it different that's fine too.

**Comment by TheDiamondYT1** [comment]
Hmm... The problem is you get method names like this

```php
$this->languageConfig->getChangePetNameNoPermissionMessage();
```

**Comment by Sandertv** [comment]
Agreed, maybe something like this; https://github.com/BlockHorizons/BlockSniper/blob/master/src/BlockHorizons/BlockSniper/data/TranslationData.php ?

**Comment by TheDiamondYT1** [comment]
Yeah

**Comment by TheDiamondYT1** [comment]
You can eliminate the use of all of that ugly code by using Config->getNested()

**Comment by Sandertv** [comment]
I could, but I prefer doing it without creating a new Config object :P

**Comment by TheDiamondYT1** [comment]
Same. Ugly code it is :)
