### ISSUE TITLE
Change spawnTo() to support a recent api3/blocks commit

### ISSUE THREAD

**Issue by TheDiamondYT1** [BlockHorizons/BlockPets#47]
Recently there was [a commit](https://github.com/pmmp/PocketMine-MP/commit/c860ff2102b04c190caa13e7d119b23df40f48be) to api3/blocks which changed the obseletes the need for `spawnTo`. I'm not sure if we support development branches but even if we don't this will be a future issue.

**Comment by Sandertv** [comment]
Also attack() and heal() functions have been changed on this branch. A new branch should probably be made for this.

**Comment by Sandertv** [comment]
To ignore the branches mess I made I'll just continue development on the master branch and remove the spawnTo + fix the attack and heal functions for the entities once api3/blocks gets merged, or at least being close to it.
