### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by oGalatico** [BlockHorizons/BlockPets#50]

**Comment by Sandertv** [comment]
I cannot resolve this with no information.

**Comment by oGalatico** [comment]
`
![screenshot_20170706-072446](https://user-images.githubusercontent.com/18704329/27907061-6c1598c4-621c-11e7-8384-1ec5aaed0847.png)

**Comment by Sandertv** [comment]
Please download the latest version.

**Comment by Sandertv** [comment]
Sorry not the latest, the file 2 commits back.
