### ISSUE TITLE
Configurable pet sizes

### ISSUE THREAD

**Issue by Herojhjh** [BlockHorizons/BlockPets#51]
can you make per petsize? so owner can control max size per pet. Like dragon soo big right? and what do you think if player maybe MVP for example or other paid rank spawn this on the server? so can you make it? its just my sugestion if you not like my sugestion you can close it.

**Comment by TheDiamondYT1** [comment]
This is probably pissible using setScale()

**Comment by Sandertv** [comment]
I'll add a max pet size for every pet.

**Comment by Herojhjh** [comment]
thanks! @Sandertv
