### ISSUE TITLE
Fatal error help

### ISSUE THREAD

**Issue by oGalatico** [BlockHorizons/BlockPets#57]
![screenshot_20170725-175707](https://user-images.githubusercontent.com/18704329/28593435-b3845a56-7162-11e7-9468-1e0ed10d157a.png)

**Comment by TheDiamondYT1** [comment]
Update your version of PocketMine-MP.

**Comment by oGalatico** [comment]
Do you have any?

**Comment by oGalatico** [comment]
Eu uso genisyspro 1.1.3

**Comment by TheDiamondYT1** [comment]
We don't support spoons, such as GenisysPro
