### ISSUE TITLE
Can't ride pets that you can ride in MCPE

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BlockHorizons/BlockPets#58]
I cant ride pigs, llamas etc.

- [x] Llamas
- [x] Pigs
- [x] Any type of horse-like mob.

**Comment by TheDiamondYT1** [comment]
@jasonwynn10 How is this invalid? At least specify why.

**Comment by jasonwynn10** [comment]
It's a well known issue which is being worked on already

**Comment by TheDiamondYT1** [comment]
@jasonwynn10 There we go ;)

**Comment by jasonwynn10** [comment]
@Sandertv has attempted to resolve this several times without luck, so this will take a while

**Comment by TheDiamondYT1** [comment]
But it still deserves fo be open

**Comment by Sandertv** [comment]
Riding Withers actually works for me.

**Comment by Sandertv** [comment]
Yeah, this is certainly a tough one. I'm really having trouble finding what is causing this.
