### ISSUE TITLE
Flying Pets can pass through blocks when you ride them

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BlockHorizons/BlockPets#63]
Flying Pets can pass through blocks when you ride them. This does not happens always, and if they go to more than 3 blocks, they stack. Plus, because I don't want to create an other issue, is this a bug, or not: I can't jump with horses.

**Comment by Sandertv** [comment]
Does this happen with any flying pet? I remember reproducing it with an enderdragon pet, but never tried it with another pet.

For the horses, I haven't yet implemented it. Only yesterday I finally found the cause of the game freezing when trying to ride horses, pigs and llamas, so I had no times to work on the jumping with horses yet. I'll work on it soon.

**Comment by MalakasPlayzMC** [comment]
I have tested it with bats, ghasts and ender dragons

**Comment by Sandertv** [comment]
Alright, looking into it.

**Comment by MalakasPlayzMC** [comment]
Bump!

**Comment by MalakasPlayzMC** [comment]
Bump v2!

**Comment by MalakasPlayzMC** [comment]
Bump v3!

**Comment by Driesboy** [comment]
BUMP v9999999

**Comment by MalakasPlayzMC** [comment]
Bump v10000000
We lost the counting...

**Comment by MalakasPlayzMC** [comment]
Bump!

**Comment by 95CivicSi** [comment]
Instead of just bumping.  You could try coding.  I've seen the request and will try to solve this, if possible, when I get time. Currently, no ETA.
