### ISSUE TITLE
Value 33044 is too large!

### ISSUE THREAD

**Issue by totor29** [BlockHorizons/BlockPets#66]
Hi,

please find new issue

Issue description :
server crash / critical error Value 3XXXX is too large!

Value 34970 is too large https://crash.pmmp.io/view/2011
Value 33044 is too large! https://crash.pmmp.io/view/2073
Value 32849 is too large!
...

issue related :
https://github.com/pmmp/PocketMine-MP/issues/1251

PocketMine version : 1.6.2dev-319
PHP version: | 7.0.17
Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64

Not tested on a clean server without plugins

Loaded plugins:
PurePerms 1.4.1-dev1 by 64FF00 & ProjectInfinity for API(s) 3.0.0-ALPHA7
BlockPets 1.1.0 by BlockHorizons for API(s) 3.0.0-ALPHA7
FactionsPro 1.4.4-dev1 by Tethered_, HostingItAll.com for API(s) 3.0.0-ALPHA7
AlwaysSpawn 2.2.3-dev1 by Philip Shilling for API(s) 3.0.0-ALPHA7
SimpleAuth 1.8.1-dev1 by PocketMine Team, shoghicp, awzaw for API(s) 3.0.0-ALPHA7
SimpleAuthHelper 2.0.5-dev1 by aliuly for API(s) 3.0.0-ALPHA7
PiggyCustomEnchants 1.0.2 by DaPigGuy for API(s) 3.0.0-ALPHA7
essentialsTP 1.1.1-dev3 by for API(s) 3.0.0-ALPHA7
ChatToDiscord 1.1.0 by eDroid for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7
Parkour 1.5.3 by jdcraft for API(s) 3.0.0-ALPHA7

thanks

**Comment by Sandertv** [comment]
Have you made sure it's actually BlockPets? Could you try removing it and see if it still occures?

**Comment by totor29** [comment]
for the moment i can not test this because my server is online. i will try to do that.
error occured since BlockPets installation.
error rarely occurs, usually with a number of players greater than 10 
others plugins 
the others plugins have been installed for a long time

thanks

**Comment by totor29** [comment]
Update 

-30 [14:44:19] [Server thread/ERROR]: Error while unloading a chunk: Value 91834 is too large!
2017-07-30 [14:44:19] [Server thread/CRITICAL]: InvalidArgumentException: "Value 91834 is too large!" (EXCEPTION) in "src/pocketmine/nbt/tag/ShortTag" at line 70

tag/ShortTag What does is mean ?
thanks

**Comment by Sandertv** [comment]
Turns out this issue can't possibly be caused by BlockPets. I'm suspecting this is an Issue from PureEntitiesX, where a projectile entity got written/saved wrongly, causing that error occasionally when the projectile gets saved again. I can't do anything about this. Sorry.

**Comment by totor29** [comment]
thanks you for this information.
can you give me some information, because PureEntitiesX is no longer installed on the server.
does it mean that world maps is corrupted ?
how to fix it ?
thanks

**Comment by Sandertv** [comment]
Sadly it seems like PureEntitiesX got an entity saved in a faulty way, and it might mean a sort of corrupted map yeah. You could search an NBT editor, go to the level.dat and try to find the projectile entity and remove it.

**Comment by totor29** [comment]
could you please advise me a NBT editor 
thanks

**Comment by Sandertv** [comment]
You could try this: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

**Comment by totor29** [comment]
thanks
