### ISSUE TITLE
[Server thread/CRITICAL]: Error: "Call to a member function hasPermission() on null" (EXCEPTION) in "BlockPets.phar/src/BlockHorizons/BlockPets/pets/Calculator" at line 56

### ISSUE THREAD

**Issue by teracube** [BlockHorizons/BlockPets#69]
Hi, 
critical error found :

[Server thread/CRITICAL]: Error: "Call to a member function hasPermission() on null" (EXCEPTION) in "BlockPets.phar/src/BlockHorizons/BlockPets/pets/Calculator" at line 56

BlockPets Dev 206
https://poggit.pmmp.io/r/9737/BlockPets.phar

PocketMine-MP_1.6.2dev-377
https://jenkins.pmmp.io/job/PocketMine-MP/377/artifact/PocketMine-MP_1.6.2dev-377_06083d6d_API-3.0.0-ALPHA7.phar

thanks

**Comment by teracube** [comment]
thank you very much ;-)

**Comment by Sandertv** [comment]
No problem! :)
