### ISSUE TITLE
"o" after pet names

### ISSUE THREAD

**Issue by NickTehUnicorn** [BlockHorizons/BlockPets#72]
After spawning a pet (in this example, an ocelot with the name CAT), there appears to be an "o" after the pet name (this makes it CATo). No difference in commands (clearpet CAT works fine) but it shows up with an o after the name.

**PocketMine version:** PocketMine-MP 1.6.2dev+poggit.1366 「Unleashed」 implementing API version 3.0.0-ALPHA7 for Minecraft: PE v1.1.0.55 (protocol version 113)
**Minecraft version:** Minecraft: Windows 10 Edition v1.1.5
**BlockPets build:** 95bbb86

![2017-08-14](https://user-images.githubusercontent.com/29836508/29267238-81f147e0-80f0-11e7-8f7d-59c3043a4a91.png)

**Comment by Sandertv** [comment]
This is not something I can do about sadly. Might I guess you're using a windows machine, or am I wrong there?
