### ISSUE TITLE
Block indestructible with plugin installed

### ISSUE THREAD

**Issue by Gigglequad** [BlockHorizons/BlockPets#73]
Just installed this plugin with PMMP via the Poggit here https://poggit.pmmp.io/p/BlockPets/1.1.0 and it seems to make it so that creation or removal of any blocks is impossible. Using latest verion of PMMP as of today, Alpha7. Anyone can verify?

**Comment by Sandertv** [comment]
BlockPets has absolutely no relation to block breaking or placing. Could you please make sure it really is this plugin that causes it?

**Comment by TheDiamondYT1** [comment]
There is no mention of `BlockPlaceEvent` or `BlockBreakEvent` anywhere in the code. It can't be BlockPets.

**Comment by Gigglequad** [comment]
Regardless, removing it allows blocks to be broken and enabling it again prevents blocks from being broken or created. It's very odd!

**Comment by Sandertv** [comment]
Wtf... Any error in console or anything when breaking or placing a block?

**Comment by Gigglequad** [comment]
WTF is right. There is no error in the console. It simply "explodes" but doesn't disappear. for placing a block it will place, then immediately remove itself in less than a second.

**Comment by Sandertv** [comment]
Please try using the latest CI build from Poggit and see if it still occures.

**Comment by Thunder33345** [comment]
try dumping plugin list and verify that you can break when the plugin is not installed (that dosent meant block pets caused it for sure but can be correlated, very edge case and unlikely but that can be caused by pre-installed plugin detecting blockpets is installed this disable breaking)

**Comment by Gigglequad** [comment]
Dumping plugin list? Sorry, I don't know what that means. If I type plugins into my console it shows Alwaysspawn, Xyz, poggit loader, and jail right now. If I add Blockpets again, blocks become indestructible. If i remove it, they return to normal.

**Comment by Sandertv** [comment]
Could you try installing BlockPets only and temporarily removing all other plugins? (Especially the jail plugin)

**Comment by Gigglequad** [comment]
Of course!

Removing all other plugins and installing only BlockPets 1.1.0 produces the same results.

**Comment by TheDiamondYT1** [comment]
This might sound a bit stupid, but try commenting out different lines of this (if you know what you're doing, of course)

https://github.com/BlockHorizons/BlockPets/blob/master/src/BlockHorizons/BlockPets/Loader.php#L221-#L235

**Comment by Gigglequad** [comment]
I don't know what I'm doing, but if you pop up a phar I'll be happy to spend most of the evening working on this with you.

**Comment by TheDiamondYT1** [comment]
I cant compile anything since the PHP build script for android aarch64 doesnt work :eyeroll: @dktapps

**Comment by Gigglequad** [comment]
that sounds pretty bad! Can you talk me through it?

**Comment by Gigglequad** [comment]
I've got access to a Ubuntu 16 box and a Windows 10 box.

**Comment by TheDiamondYT1** [comment]
I'm too lazy and it's 11:20pm

**Comment by Gigglequad** [comment]
6:33pm here. Maybe tomorrow. That you don't want to mess with it at almost Midnight isn't lazy. Never say you're lazy. It's just too late at night! ;)

**Comment by TheDiamondYT1** [comment]
lol whoops

**Comment by Sandertv** [comment]
Have you made sure you're not in some kind of spawn protection?

**Comment by Gigglequad** [comment]
Yes, the problem persists even after 30 minutes of playing.

**Comment by Sandertv** [comment]
I failed to understand if you tried installing the latest development build here: https://poggit.pmmp.io/ci/BlockHorizons/BlockPets/BlockPets
Did you try that?

**Comment by Shiny-andKittens** [comment]
As far as I know this is an open issue on the PMMP repo
