### ISSUE TITLE
Some problems with PurePerms

### ISSUE THREAD

**Issue by Yexeed** [BlockHorizons/BlockPets#88]
When player joins on my server, server throwing some errors in console and player doesnt have ANY commands in his command map. Its happening when blockpets registering a commands for player.  I dont know how to fix so i created an issue
```
Невозможно обработать событие 'pocketmine\event\player\PlayerLoginEvent' в 'PurePerms v1.4.1-1.alpha8': Cannot use object of type stdClass as array в _64FF00\PurePerms\PPListener`
`Error: "Cannot use object of type stdClass as array" (EXCEPTION) in "/plugins/BlockPets_1/src/BlockHorizons/BlockPets/commands/BaseCommand" at line 63
```
BlockPets code:
```
`public function generateCustomCommandData(Player $player): array{
		$commandData = parent::generateCustomCommandData($player);
		$commandData["permission"] = $this->getPermission();
		$commandData["overloads"]["default"]["input"]["parameters"] = CommandOverloads::getOverloads($this->getName());

		return $commandData;
	}
```
PP:
```
    public function getPermissions(IPlayer $player, $levelName)
    {
        // TODO: Fix this
        $group = $this->userDataMgr->getGroup($player, $levelName);
        $groupPerms = $group->getGroupPermissions($levelName);
        $userPerms = $this->userDataMgr->getUserPermissions($player, $levelName);

       return array_merge($groupPerms, $userPerms);
    }
```

**Comment by Sandertv** [comment]
Server software? Version?

**Comment by TheDiamondYT1** [comment]
@Sandertv It says PurePerms v1.4.1.1-alpha8 which shows us the server software is running ALPHA8 which narrows it down to the latest builds.

**Comment by Sandertv** [comment]
This is issue does not occur on PocketMine-MP.

**Comment by Yexeed** [comment]
I'm using last genisys build so genisys using old API and in all tasks and commands i have to remove some part of code (like 
(`CommandSender $sender, string $commandLabel, array $args): bool{}`
to 
`(CommandSender $sender, $commandLabel, array $args){}//without bool and string`

**Comment by TheDiamondYT1** [comment]
Genisys is dumb.
